### ISSUE TITLE
Initializations

### ISSUE THREAD

**Issue by qobilidop** [xiongliyang219/transfer-learning#4]
By default, a keras `Dense` layer uses the `glorot_uniform` initialization. Is it good enough? Or do we want to use something else? See the [doc](https://keras.io/initializations/) for available options.

**Comment by xiongliyang219** [comment]
I used "he_normal: Gaussian initialization scaled by fan_in" in the initial version.

**Comment by xiongliyang219** [comment]
why it is still adadelta

**Comment by qobilidop** [comment]
Because it's supposed to be converging fast.

**Comment by qobilidop** [comment]
And there's no parameter to tune, which is good.
